### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by Niceguy1337** [azerothcore/mod-eluna#50]
14>G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\LuaEngine\ElunaUtility.h(55,36): error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt. (Quelldatei wird kompiliert G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp)
14>G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\LuaEngine\ElunaUtility.h(55,26): error C2146: Syntaxfehler: Fehlendes ";" vor Bezeichner "ElunaQuery" (Quelldatei wird kompiliert G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp)
14>G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\LuaEngine\ElunaUtility.h(56,1): warning C4005: "ASSERT": Makro-Neudefinition (Quelldatei wird kompiliert G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp)
14>G:\WoW Server\AzerothCore\Core\src\common\Debugging\Errors.h(68): message : Siehe vorherige Definition von "ASSERT" (Quelldatei wird kompiliert G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp)
14>G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\LuaEngine\ElunaEventMgr.h(22,10): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Platform/Define.h": No such file or directory (Quelldatei wird kompiliert G:\WoW Server\AzerothCore\Core\modules\mod-eluna\src\ElunaLuaEngine_SC.cpp)

**Comment by 55Honey** [comment]
Hello @Niceguy1337
Your compile errors are not related to Eluna being faulty, but to some detail of your toolchain. It compiles just fine (tested with `AzerothCore rev. ea453acec0f1 2022-07-02 17:53:03`)
Maybe try without modules?

If else fails, you should ask on Stackoverflow and link the question on AC discord.
Also, German language is hard or impossible to read for many contributors. You should post in English and give details instead of just copy-pasting an error message.
