### ISSUE TITLE
use mod-eluna not valid

### ISSUE THREAD

**Issue by Mrming1994** [azerothcore/mod-eluna#91]
Hi,

I am using the docker way of setting up Azerothcore with the current version and installed this eluna module, also with current version.

![微信图片_20230202132343](https://user-images.githubusercontent.com/43674158/216238987-cfa239d9-3947-42d7-8cc1-382d0f8e078f.png)
![微信图片_20230202132350](https://user-images.githubusercontent.com/43674158/216238994-35794d4a-51ab-4092-9aac-da1d21f0af0d.png)

Where should I put lua_scripts

**Comment by 55Honey** [comment]
Lua scripts go (with default conf) into a folder called `lua_scripts` next to your worldserver binaries.

After successfully compiling, this folder should be created automatically. Please track it.

**Comment by Mrming1994** [comment]
hi, 55Honey

I use ./acore.sh docker build command to make 

success done but not find this folder should be created automatically

Please help me. thanks

![微信图片_20230202203142](https://user-images.githubusercontent.com/43674158/216327585-c32294e5-cf71-4408-9dc6-55da2ecfb311.png)

**Comment by 55Honey** [comment]
You are showing only files from the source. This is not where the compiled worldserver searches for files.
Check where the worldserver binaries are. If the `lua_scripts` folder does not exist, the module was not compiled.

Your issue is not related to mod-eluna. It seems to be a docker-related problem, so you're better off asking in the AC support discord.

**Comment by 55Honey** [comment]
I'm wondering if you solved it @Mrming1994 ?

**Comment by Baudin999** [comment]
Hi, maybe the wrong place to continue this conversation, but I am having exactly the same problem but one step further along. 

I have pulled the latest version from github of azerothcore (2 days ago).
I have installed the mod like this (btw, I am on Windows):

```
cd modules
git clone https://github.com/azerothcore/mod-eluna.git mod-eluna
```

I rebuild by doing:

```
docker compose up --build -d
```

This builds and starts the server. The `lua_scripts` folder is successfully created. 

When I add the following script:

```
local function OnLogin(event, player)
    local playerName = player:GetName()
    player:SendBroadcastMessage("Hello " .. playerName .. "!")
    print("Player " .. playerName .. " has logged in. Hello message sent.")
end

RegisterPlayerEvent(3, OnLogin) 
```

Nothing happens when I start the server. 

I can attack to my world server: `docker attach ac-worldserver`
And execute: `reload eluna` nothing happens

```
AC> reload eluna
AC> AC>
```

I also, when the server starts, do not see any server logs in docker.
